{
    config,
    pkgs,
    lib,
    ...
}:
with lib;
let
    cfg = config.nixos-utilities.systems.router;
    routerConfig = cfg.config;
    nameservers =
        routerConfig.nameservers or (map (net: net.ipv4.gateway) (attrValues routerConfig.lan.networks));
    # Helper to extract primary domain from DNS A records
    extractPrimaryDomain =
        aRecords:
        if aRecords == { } || aRecords == null then
            null
        else
            let
                firstRecord = builtins.head (builtins.attrNames aRecords);
                parts = lib.splitString "." firstRecord;
                numParts = builtins.length parts;
            in
            if numParts >= 2 then
                "${builtins.elemAt parts (numParts - 2)}.${builtins.elemAt parts (numParts - 1)}"
            else
                null;

    # Get primary domain for search suffix (from HOMELAB network)
    primaryDomain = extractPrimaryDomain (
        routerConfig.lan.${routerConfig.lan.primaryDomain}.dns.records.a_records or { }
    );
in
{
    imports = [
        ./router.nix
        ./cake.nix
        ./dns.nix
        ./dyndns.nix
    ];

    config = mkIf cfg.enable {
        services.resolved.enable = true;
        networking.nameservers = nameservers;

        # Explicitly manage /etc/resolv.conf to ensure it's populated on boot
        # This ensures nameservers are available even if networking module doesn't write it
        environment.etc."resolv.conf" = mkForce {
            text = ''
                # Generated by NixOS - do not edit manually
                ${lib.concatMapStringsSep "\n" (ns: "nameserver ${ns}") nameservers}
                ${lib.optionalString ((routerConfig.domain or "") != "") "search ${routerConfig.domain}"}
            '';
            mode = "0644";
        };
        # Add search domain so we can use short hostnames (e.g., "ssh hera" instead of "ssh hera.jeandr.net")
        # Use explicit domain from router-config.nix, fallback to extracted domain from DNS records
        networking.search =
            if (routerConfig.domain or "") != "" then
                [ routerConfig.domain ]
            else
                lib.optional (primaryDomain != null) primaryDomain;
        environment.systemPackages = [
            pkgs.speedtest-cli
        ];
    };
}
